language: node_js
dist: xenial
node_js: lts/*
sudo: true

addons:
  firefox: latest
  chrome: stable

# limit the Travis 'build on push' feature to master and dist branches only
branches:
  only:
   - master

install:
  - yarn install
  - yarn build

  # bundlesize
  - yarn global add bundlesize@^0.18.0
  - bundlesize -f dist/sweetalert2.all.min.js -s 16kB

  # prevent adding devDependencies with a shitload of subdependencies
  - if [ `yarn list | wc -l` -gt 4000 ]; then
      exit 1;
    fi

script:
  - yarn run check

notifications:
  email:
    on_success: never

after_success:
  # report coverage to coveralls.io
  - yarn global add coveralls@3
  - cat ./coverage/lcov.info | coveralls
